#############################################################################
# Makefile for building: QOSCAR2
# Generated by qmake (2.01a) (Qt 4.6.2) on: ?? ???? 7 19:40:34 2010
# Project:  QOSCAR2.pro
# Template: app
# Command: /home/rankor/qtsdk-2010.02/qt/bin/qmake -spec ../../../../rankor/qtsdk-2010.02/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile QOSCAR2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../../rankor/qtsdk-2010.02/qt/mkspecs/linux-g++ -I. -I../../../../rankor/qtsdk-2010.02/qt/include/QtCore -I../../../../rankor/qtsdk-2010.02/qt/include/QtNetwork -I../../../../rankor/qtsdk-2010.02/qt/include/QtGui -I../../../../rankor/qtsdk-2010.02/qt/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/rankor/qtsdk-2010.02/qt/lib
LIBS          = $(SUBLIBS)  -L/home/rankor/qtsdk-2010.02/qt/lib -lQtGui -L/home/rankor/qtsdk-2010.02/qt/lib -L/usr/X11R6/lib -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/rankor/qtsdk-2010.02/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		qoscar/qoscar.cpp \
		qoscar/qoscarsocket.cpp \
		qoscar/qoscarba.cpp \
		qoscar/qoscarbasic.cpp \
		qoscar/qoscarident.cpp \
		qoscar/qoscaroservice.cpp \
		qoscar/qoscaricbm.cpp moc_mainwindow.cpp \
		moc_qoscar.cpp \
		moc_qoscarsocket.cpp \
		moc_qoscaroservice.cpp \
		moc_qoscaricbm.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qoscar.o \
		qoscarsocket.o \
		qoscarba.o \
		qoscarbasic.o \
		qoscarident.o \
		qoscaroservice.o \
		qoscaricbm.o \
		moc_mainwindow.o \
		moc_qoscar.o \
		moc_qoscarsocket.o \
		moc_qoscaroservice.o \
		moc_qoscaricbm.o
DIST          = ../../../../rankor/qtsdk-2010.02/qt/mkspecs/common/g++.conf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/common/unix.conf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/common/linux.conf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/qconfig.pri \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/qt_functions.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/qt_config.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/exclusive_builds.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/default_pre.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/debug.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/default_post.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/warn_on.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/qt.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/unix/thread.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/moc.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/resources.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/uic.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/yacc.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/lex.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/include_source_dir.prf \
		QOSCAR2.pro
QMAKE_TARGET  = QOSCAR2
DESTDIR       = 
TARGET        = QOSCAR2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QOSCAR2.pro  ../../../../rankor/qtsdk-2010.02/qt/mkspecs/linux-g++/qmake.conf ../../../../rankor/qtsdk-2010.02/qt/mkspecs/common/g++.conf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/common/unix.conf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/common/linux.conf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/qconfig.pri \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/qt_functions.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/qt_config.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/exclusive_builds.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/default_pre.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/debug.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/default_post.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/warn_on.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/qt.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/unix/thread.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/moc.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/resources.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/uic.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/yacc.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/lex.prf \
		../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/include_source_dir.prf \
		/home/rankor/qtsdk-2010.02/qt/lib/libQtGui.prl \
		/home/rankor/qtsdk-2010.02/qt/lib/libQtCore.prl \
		/home/rankor/qtsdk-2010.02/qt/lib/libQtNetwork.prl
	$(QMAKE) -spec ../../../../rankor/qtsdk-2010.02/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile QOSCAR2.pro
../../../../rankor/qtsdk-2010.02/qt/mkspecs/common/g++.conf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/common/unix.conf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/common/linux.conf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/qconfig.pri:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/qt_functions.prf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/qt_config.prf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/exclusive_builds.prf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/default_pre.prf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/debug.prf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/default_post.prf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/warn_on.prf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/qt.prf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/unix/thread.prf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/moc.prf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/resources.prf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/uic.prf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/yacc.prf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/lex.prf:
../../../../rankor/qtsdk-2010.02/qt/mkspecs/features/include_source_dir.prf:
/home/rankor/qtsdk-2010.02/qt/lib/libQtGui.prl:
/home/rankor/qtsdk-2010.02/qt/lib/libQtCore.prl:
/home/rankor/qtsdk-2010.02/qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../../rankor/qtsdk-2010.02/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile QOSCAR2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QOSCAR21.0.0 || $(MKDIR) .tmp/QOSCAR21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QOSCAR21.0.0/ && $(COPY_FILE) --parents mainwindow.h qoscar/qoscar.h qoscar/qoscarsocket.h qoscar/qoscarba.h qoscar/qoscarbasic.h qoscar/qoscarident.h qoscar/qoscarstuff.h qoscar/qoscaroservice.h qoscar/qoscaricbm.h .tmp/QOSCAR21.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp qoscar/qoscar.cpp qoscar/qoscarsocket.cpp qoscar/qoscarba.cpp qoscar/qoscarbasic.cpp qoscar/qoscarident.cpp qoscar/qoscaroservice.cpp qoscar/qoscaricbm.cpp .tmp/QOSCAR21.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/QOSCAR21.0.0/ && (cd `dirname .tmp/QOSCAR21.0.0` && $(TAR) QOSCAR21.0.0.tar QOSCAR21.0.0 && $(COMPRESS) QOSCAR21.0.0.tar) && $(MOVE) `dirname .tmp/QOSCAR21.0.0`/QOSCAR21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QOSCAR21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_qoscar.cpp moc_qoscarsocket.cpp moc_qoscaroservice.cpp moc_qoscaricbm.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_qoscar.cpp moc_qoscarsocket.cpp moc_qoscaroservice.cpp moc_qoscaricbm.cpp
moc_mainwindow.cpp: qoscar/qoscar.h \
		qoscar/qoscarstuff.h \
		qoscar/qoscarbasic.h \
		qoscar/qoscarba.h \
		qoscar/qoscarsocket.h \
		qoscar/qoscarident.h \
		qoscar/qoscaroservice.h \
		qoscar/qoscaricbm.h \
		mainwindow.h
	/home/rankor/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_qoscar.cpp: qoscar/qoscarstuff.h \
		qoscar/qoscarbasic.h \
		qoscar/qoscarba.h \
		qoscar/qoscarsocket.h \
		qoscar/qoscarident.h \
		qoscar/qoscaroservice.h \
		qoscar/qoscaricbm.h \
		qoscar/qoscar.h
	/home/rankor/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) qoscar/qoscar.h -o moc_qoscar.cpp

moc_qoscarsocket.cpp: qoscar/qoscarba.h \
		qoscar/qoscarsocket.h
	/home/rankor/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) qoscar/qoscarsocket.h -o moc_qoscarsocket.cpp

moc_qoscaroservice.cpp: qoscar/qoscarstuff.h \
		qoscar/qoscarbasic.h \
		qoscar/qoscarba.h \
		qoscar/qoscaroservice.h
	/home/rankor/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) qoscar/qoscaroservice.h -o moc_qoscaroservice.cpp

moc_qoscaricbm.cpp: qoscar/qoscarstuff.h \
		qoscar/qoscarbasic.h \
		qoscar/qoscarba.h \
		qoscar/qoscaricbm.h
	/home/rankor/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) qoscar/qoscaricbm.h -o moc_qoscaricbm.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/rankor/qtsdk-2010.02/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		qoscar/qoscar.h \
		qoscar/qoscarstuff.h \
		qoscar/qoscarbasic.h \
		qoscar/qoscarba.h \
		qoscar/qoscarsocket.h \
		qoscar/qoscarident.h \
		qoscar/qoscaroservice.h \
		qoscar/qoscaricbm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		qoscar/qoscar.h \
		qoscar/qoscarstuff.h \
		qoscar/qoscarbasic.h \
		qoscar/qoscarba.h \
		qoscar/qoscarsocket.h \
		qoscar/qoscarident.h \
		qoscar/qoscaroservice.h \
		qoscar/qoscaricbm.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qoscar.o: qoscar/qoscar.cpp qoscar/qoscar.h \
		qoscar/qoscarstuff.h \
		qoscar/qoscarbasic.h \
		qoscar/qoscarba.h \
		qoscar/qoscarsocket.h \
		qoscar/qoscarident.h \
		qoscar/qoscaroservice.h \
		qoscar/qoscaricbm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qoscar.o qoscar/qoscar.cpp

qoscarsocket.o: qoscar/qoscarsocket.cpp qoscar/qoscarsocket.h \
		qoscar/qoscarba.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qoscarsocket.o qoscar/qoscarsocket.cpp

qoscarba.o: qoscar/qoscarba.cpp qoscar/qoscarba.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qoscarba.o qoscar/qoscarba.cpp

qoscarbasic.o: qoscar/qoscarbasic.cpp qoscar/qoscarbasic.h \
		qoscar/qoscarba.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qoscarbasic.o qoscar/qoscarbasic.cpp

qoscarident.o: qoscar/qoscarident.cpp qoscar/qoscarident.h \
		qoscar/qoscarbasic.h \
		qoscar/qoscarba.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qoscarident.o qoscar/qoscarident.cpp

qoscaroservice.o: qoscar/qoscaroservice.cpp qoscar/qoscaroservice.h \
		qoscar/qoscarstuff.h \
		qoscar/qoscarbasic.h \
		qoscar/qoscarba.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qoscaroservice.o qoscar/qoscaroservice.cpp

qoscaricbm.o: qoscar/qoscaricbm.cpp qoscar/qoscaricbm.h \
		qoscar/qoscarstuff.h \
		qoscar/qoscarbasic.h \
		qoscar/qoscarba.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qoscaricbm.o qoscar/qoscaricbm.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_qoscar.o: moc_qoscar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qoscar.o moc_qoscar.cpp

moc_qoscarsocket.o: moc_qoscarsocket.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qoscarsocket.o moc_qoscarsocket.cpp

moc_qoscaroservice.o: moc_qoscaroservice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qoscaroservice.o moc_qoscaroservice.cpp

moc_qoscaricbm.o: moc_qoscaricbm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qoscaricbm.o moc_qoscaricbm.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

